### PR TITLE
Added macOS 10.15 Catalina reporting.

### PR DESCRIPTION
**Pull request by kevinmcox**

### CODE REVIEW

**Comment by tuxudo** [comment]
This changes too much to update to the latest OS versions. Only line 40 should be changed with new OS versions

**Comment by kevinmcox** [comment]
I guess it really depends on if we want to call 10.15.0 the "most current OS" even though it is just in beta.

We also have to account for the change in the Mac Pros at line 75. 

So alternatively I could just change the $most_current_os to 10.15.0 and then hard code in the maximum supported version for the MacPro5,1 as "10.14.5" and then continue to update that line as the Mojave version is incremented in the future.

Either option will get the job done so I'm happy to switch it around the other way if you'd prefer. It'll only take me a few minutes to do.

**Comment by tuxudo** [comment]
Looks good, may want to change the 5,1 Mac Pro to 10.14.6. Don't know if we should include the MacPro 4,1 as limited to 10.13.6 or not

**Comment by kevinmcox** [comment]
Good catch, I've got a MacPro4,1 at home and didn't even notice.

That said, now that I think about it, I'm pretty sure that a stock MacPro4,1 is limited to 10.11.6 actually. You can easily get it to 10.13.6 by flashing the firmware so it thinks it is a 5,1 and then to 10.14 with a new video card.

But should we just be reporting the officially supported OS by Apple with the module? This would give an accurate reporting to admins who don't know about the workarounds while not hampering admins who know you can easily get a newer OS on the ten year old hardware with some tricks.

**Comment by tuxudo** [comment]
You're right about the 4,1 being limited to 10.11.6. We should stick with the official Apple maximum supported

**Comment by kevinmcox** [comment]
OK, made that additional change to the MacPro4,1.

**Pull request merged**
